name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        subdirectory: API/
        github_repo_id: dhruv4023/ExpenseTrackerApp
        huggingface_repo_id: dhruv4023/appServer
        repo_type: space
        space_sdk: docker
        hf_token: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
